name: Close Pull Request

on:
    pull_request_target:
        types: [ opened ]

permissions:
    pull-requests: write
    workflow: write

jobs:
    close:
        uses: cashier-provider/.github/.github/workflows/close-pull-request.yml@main
