name: Close Pull Request

on:
    pull_request_target:
        types: [ opened ]

permissions: write-all

jobs:
    close:
        uses: cashier-provider/.github/.github/workflows/close-pull-request.yml@main
